Unify system unit and script content
Change-Id: I13fbcf099f968224ba19bb20377dbe3a9028b897

diff --git a/var/lib/lastore/scripts/build_system_info b/var/lib/lastore/scripts/build_system_info
--- a/var/lib/lastore/scripts/build_system_info
+++ b/var/lib/lastore/scripts/build_system_info
@@ -1,5 +1,20 @@
 #!/bin/bash
 
+function prepare()
+{
+    # The unit is typically launched by apt hooks,
+    # so we just directly exit failed when the apt-get is still running, and restart it after 1 seconds.
+    if /usr/bin/pgrep apt-get > /dev/null; then
+        echo "apt-get is running, please try it later"
+        exit 1;
+    fi
+
+    if [ "$(/usr/bin/busctl get-property com.deepin.lastore /com/deepin/lastore com.deepin.lastore.Manager SystemOnChanging)" != "b false" ]; then
+        echo "system is on changing, please try it later"
+        exit -1;
+    fi
+}
+
 function systemd_build_system_info()
 {
     systemctl start lastore-build-system-info.service
@@ -11,6 +26,8 @@ function build_system_info_now()
     /usr/bin/lastore-tools update -j=desktop -o /var/lib/lastore/
     /var/lib/lastore/scripts/build_safecache.sh > /dev/null
 }
+
+prepare
 
 #We should clean the update_infos.json early, otherwise
 #actions, like systemctl stop, reboot immediately after apt-get
